### ISSUE TITLE
Where are the resources?

### ISSUE THREAD

**Issue by dertseha** [ccpgames/ccpwgl#11]
I've found that the resource paths used in the demos are similar to what can be found in some of the SDEs (Static Data Export). But a quick cross check with other paths shows me that apparently no other are available on the CDN.

A dedicated discovery mechanism is not immediately necessary, with the paths available in the SDE, it would be enough if the files were available on the CDN. Can you make them available or is some general overhaul planned, changing all the paths?

**Comment by cppctamber** [comment]
**DDS/PNG Files**
DDS files are converted to png files in three different formats:

*.dds.0.png (High quality)
*.dds.1.png (Medium quality)
*.dds.2.png (low quality)

**Cube Maps**
.cube map extentions are actually .png files, but they retain the .cube extension so that ccpwgl can handle them in a specific way.

**WiS**
WiS stuff is not ccpwgl compatible.

**Resource Files**
Resource files can be found: http://web.ccpgamescdn.com/ccpwgl/res.??????.json
Where ?????? is the current ccpwgl version.

**Older Resource Files**
Older res files (including Jove Ships and pgs ships) can be found in the original ccpwgl directory but most of the .red files are no longer compatible. They can be fixed with manual editing, let me know if you need help.

This issue has been addresses to some degree and may be able to be closed.

**Comment by cppctamber** [comment]
*Space Object Factory Materials*
This is currently the only resource that is missing, and is required for designer skins.
