### ISSUE TITLE
Animations and Ray Casting

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#208]
Hi @filipppavlov,

Trying to figure out how to take an objects current animation state into consideration when ray casting against it's Tw2GeometryResource, Tw2Mesh and Tw2 Mesh Area. 

The Tw2Animation, Tw2Bone, Tw2Skeleton (and the others) objects get quite deep and there are a lot of them and I'm having trouble figuring out how to transform the local vertices to where ever they currently are when animated. Could you let me know if this would be possible without rewriting the vertex shaders in JS as Aurora from #devfleet suggests :3

Thanks. :3

**Comment by filipppavlov** [comment]
This one is tricky. In Eve client we use GPU to do ray casting. It solves a problem of picking against animated things, but has its own downsides.
If you need pointers to get started with GPU picking I can create a sample for you.
For CPU picking you'd either use approximate geometry (spheres or boxes instead of ships) or go full force and have all geometry meshes on CPU and run skinning there. For that you don't really need all that animation/bone mess. In the end you have your array of bone transforms that you can use directly from EveSpaceObject._perObjectData (look for JointMat).

**Comment by cppctamber** [comment]
I currently force systemmirror for my for my current ray casting system which works well although there are some costs for bigger scenes with lots of unique meshes. If I can figure out which part of the mesh is animated perhaps using colour picking will be faster. We can leave that GPU example for now, the animations haven't yet caused an issues and was just looking towards the future.

Thanks for the feed back!
