### ISSUE TITLE
MeshLineArea Rendering

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#210]
The rendering function for drawing `Tw2MeshLineAreas` results in some extra ancillary lines:

![lines](https://cloud.githubusercontent.com/assets/7591350/18124503/a3abc9aa-6fc6-11e6-9e49-a24664ecec98.jpg)

Not sure if I am using this wrong and it isn't supposed to work on a standard object, or if it's a bug. I've also tried the `res:/graphics/effect.gles2/managed/space/visualizer/wireframe.sm_hi` shader but this results in a solid white coloured object. 

Any help would be appreciated :)

**Comment by filipppavlov** [comment]
If I remember I tried using those for the map. And Tw2MeshLineArea expects geometry with line lists instead of triangles, so it can't be used with "normal" geometry. 
Unfortunately WebGL doesn't have wireframe fill mode, so rendering wireframes is not straightforward. You'd need to create an alternative index buffer with line list from the original IB with triangles.

**Comment by cppctamber** [comment]
Thanks :)
