### ISSUE TITLE
Feature Request: Add CCPs physics engine

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/ccpwgl#248]
It would be really nice to see the physics engine ccp uses in this project aswell.

Movement, collision and system navigation (warping) would be really awesome and could potentially reduce storage size of tournament recordings, processing overhead and would allow for easier animation of ccpwgl scenes.

**Comment by Robbilie** [comment]
@filipppavlov suggested plugging in a third party lib which by default is not a bad idea but it would still require tweaks to make collision, slowdown and warping and such work bc of how ccp implemented these
(if this would be used for replays an accurate representation is required…)

**Comment by filipppavlov** [comment]
There are a few reasons I am really hesitant about this. First of all CCPWGL project is purely a graphics thing. That's why it doesn't have physics, audio or any gameplay elements (although technically all of them are doable). Secondly, physics, in particular, is totally outside my area of expertise or interest:)
Even if anyone would re-implement Eve physics engine for JS it would not be of much help without all the initial parameters for ships (mass, max speed, acceleration, etc.; and some of those also depend on pilot skills and other things) and I am not sure CCP would be willing to distribute those parameters because this is too much tied to gameplay.

**Comment by Robbilie** [comment]
i am aware of the first part, id think of it as a plugin for ccpwgl. that its not your expertise, well, i was told you like to fiddle with stuff so… :D 
the initial params are no problem, they should all be in the sde and esi, available via general info or through dogma :)

**Comment by Robbilie** [comment]
i started something last night which would allow for using the ballpark eve uses via a remote interface, not sure how far i will get and it will involve a lot of fiddling  but well:
https://github.com/Robbilie/destiny/

**Comment by cppctamber** [comment]
Had a discussion regarding this with Fillip and it isn't something that is planned due to the library being a graphics engine (as per his comments above). I will however be converting the ccpwgl.js file to classes which will be included with the core module (so there is only one library to load) and in the process I can add some bounds/physics properties/ methods to the space object classes so you can hook an external physics library up to them.
