### ISSUE TITLE
Planets always render behind objects

### ISSUE THREAD

**Issue by cppctamber** [ccpgames/ccpwgl#39]
Planets always render behind objects even when they are in front of them.
While this looks intentional, is this something that could be changed?

![planet_example](https://cloud.githubusercontent.com/assets/7591350/8736692/07879072-2c6f-11e5-93b3-ee830c582bcd.jpg)

**Comment by filipppavlov** [comment]
fixed as much as possible in 205ce269eb790ef5e1884a6785ee45c62f5f1385
planet should be fine, but the atmosphere will still be sorted incorrectly

**Comment by cppctamber** [comment]
Hi Filipp, 

Looks like secondary planet geometry like rings and shattered rocks also sorted incorrectly. Is this a solvable issue?

![image](https://cloud.githubusercontent.com/assets/7591350/18607352/3c5f4460-7d1e-11e6-912f-efda6af9a82d.png)

**Comment by filipppavlov** [comment]
I'll take a look. How do you get shattered rocks into the scene?

**Comment by cppctamber** [comment]
Apologies:

```
dx9/model/worldobject/planet/shatteredplanet.red 
dx9/model/worldobject/planet/shatteredatmosphere.red 

dx9/model/worldobject/planet/template/shattered/p_shattered_01.red 
dx9/model/worldobject/planet/template/shattered/p_shattered_02.red 
dx9/model/worldobject/planet/template/shattered/p_shattered_03.red 
dx9/model/worldobject/planet/template/shattered/p_shattered_04.red 
dx9/model/worldobject/planet/template/shattered/p_shattered_05.red 
```

**Comment by cppctamber** [comment]
I take it that they have their own clipping planes?

![image](https://cloud.githubusercontent.com/assets/7591350/18614804/40fbe808-7dea-11e6-853c-6348f7329059.png)

**Comment by filipppavlov** [comment]
There's not much we can do there. Planets are rendered separately with a different projection matrix. It is done to avoid precision problems at their sizes/distances. This is why sorting between them and "normal" objects would never work. We mostly get away with this in the client because planets (except possibly moons) are so large that you are not supposed to see anything behind them. Shattered rocks are part of the planet, so they won't play well with other objects either.
